name: grpcbin image build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_URL: ghcr.io/kyma-project/networking-dev-tools/grpcbin
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64 Docker image
        uses: docker/build-push-action@v7
        with:
          file: grpcbin/Dockerfile
          context: grpcbin
          platforms: linux/amd64
          provenance: false
          push: true
          tags: ${{ env.REGISTRY_URL }}:${{ github.sha }}-amd64,${{ env.REGISTRY_URL }}:amd64
      - name: Build arm64 Docker image
        uses: docker/build-push-action@v7
        with:
          file: grpcbin/Dockerfile
          context: grpcbin
          platforms: linux/arm64
          provenance: false
          push: true
          tags: ${{ env.REGISTRY_URL }}:${{ github.sha }}-arm64,${{ env.REGISTRY_URL }}:arm64
      - name: Build latest manifest
        shell: bash
        run: |
          docker manifest create ${{ env.REGISTRY_URL }}:latest \
          ${{ env.REGISTRY_URL }}:amd64 ${{ env.REGISTRY_URL }}:arm64
      - name: Push latest manifest
        shell: bash
        run: |
          docker manifest push ${{ env.REGISTRY_URL }}:latest

